//
//  HeaderSublineVM.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout
import RxFlow
import RxSwift
import RxCocoa

struct HeaderSubline: MagazineSupplementaryDataType {

    let heightMode: MagazineLayoutHeaderHeightMode = .dynamic
    let title: String

    init(title: String) {
        self.title = title
    }

    var diffHash: Int {
        return title.hashValue
    }

    func configurator() -> SupplementaryCellConfigurator {
        return HeaderSublineConfigurator(item: self)
    }
}

